language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - zip
            - gzip
            - git
            - curl

install:
    - "cpanm --quiet --notest JSON LWP::Simple Text::CSV File::Slurp Bio::Perl"
    - "wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-2.7.1+-x64-linux.tar.gz"
    - "mkdir bin"
    - "curl https://raw.githubusercontent.com/tseemann/any2fasta/master/any2fasta > bin/any2fasta"
    - "chmod +x bin/any2fasta"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-2.7.1+/bin:$PATH"

script:
    - "abricate --setupdb"
    - "abricate --version"
    - "abricate --help"
    - "abricate --check"
    - "abricate --list"
    - "! abricate --doesnotexist"
    - "! abricate --threads 0"
    - "abricate test/assembly.fa > 1.tab"
    - "abricate test/assembly.fa.gz > 2.tab"
    - "abricate test/assembly.gbk > 3.tab"
    - "abricate test/assembly.gbk.gz > 4.tab"
    - "abricate --summary {1,2,3,4}.tab > summary.tab"
    - "for DB in `abricate --list | cut -f1`; do abricate --db $DB test/assembly.fa > /dev/null ; done"
    - "abricate-get_db --help"
    - "abricate-get_db --db card --dbdir ."
