language: perl

perl:
    - "5.14"
    - "5.26"

sudo: false
    
addons:
    apt:
        packages:
            - ncbi-blast+
            - emboss
            - zip
            - gzip

install:
    - "cpanm JSON LWP::Simple Text::CSV File::Slurp Bio::Perl"

before_script:
    - "bin/abricate --setupdb"

script:
    - "bin/abricate --version"
    - "bin/abricate --help"
    - "bin/abricate --check"
    - "bin/abricate --list"
    - "bin/abricate --quiet test/assembly.fa"
    - "bin/abricate --quiet test/assembly.fa.gz"
    - "bin/abricate --quiet test/assembly.gbk"
    - "bin/abricate --quiet test/assembly.gbk.gz"
    - "bin/abricate --list | cut -f1 > dbs.txt"
    - "for DB in `bin/abricate --list`; do bin/abricate --db $DB --quiet test/assembly.fa ; done"
