language: perl

perl:
    - "5.14"
    - "5.26"

sudo: false
    
addons:
    apt:
        packages:
            - ncbi-blast+
            - emboss
            - zip
            - gzip
            - bioperl
            - libjson-perl
            - libwww-perl
            - libtext-csv-perl
            - libfile-slurp-perl

install:
    - "bin/abricate --setupdb"

script:
    - "bin/abricate --version"
    - "bin/abricate --help"
    - "bin/abricate --check"
    - "bin/abricate --list"
