language: perl

perl:
    - "5.14"

sudo: false
    
addons:
    apt:
        packages:
            - emboss
            - zip
            - gzip

install:
    - "cpanm JSON LWP::Simple Text::CSV File::Slurp Bio::Perl"
    - "wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.6.0+-x64-linux.tar.gz"
    - "tar zxvf ncbi-blast-2.6.0+-x64-linux.tar.gz"
    - "export PATH=$PWD/bin:$PWD/ncbi-blast-2.6.0+/bin:$PATH"

script:
    - "bin/abricate --setupdb"
    - "abricate --version"
    - "abricate --help"
    - "abricate --check"
    - "abricate --list"
    - "abricate --quiet test/assembly.fa"
    - "abricate --quiet test/assembly.fa.gz"
    - "abricate --quiet test/assembly.gbk"
    - "abricate --quiet test/assembly.gbk.gz"
    - "abricate --list | cut -f1 > dbs.txt"
    - "for DB in `abricate --list | cut -f1`; do abricate --db $DB --quiet test/assembly.fa ; done"
